version: '3.3'
services:
  server:
    build: .
    ports:
      - "2999:2999"
      - "3000:3000"
      - "3001:3001"
    volumes:
      - eco_data:/eco_server/Storage
    restart: always

volumes:
  eco_data:
